context.objects = [
    { factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "mic-dummy-persistente"
            node.description = "Microfono Dummy 100%"
            media.class      = "Audio/Source/Virtual"
            audio.position   = [ FL FR ]
        }
    }
]
